# Generated by Django 6.0.2 on 2026-02-04 21:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('heartbeat_period_seconds', models.PositiveIntegerField(default=60, help_text='Expected interval between heartbeats in seconds (minimum 10)')),
                ('grace_period_seconds', models.PositiveIntegerField(default=30, help_text='Extra time before marking as offline in seconds (minimum 10)')),
                ('telegram_bot_token', models.CharField(max_length=100)),
                ('telegram_chat_id', models.CharField(max_length=50)),
                ('api_key', models.CharField(editable=False, max_length=64, unique=True)),
                ('current_power_status', models.CharField(choices=[('unknown', 'Unknown'), ('on', 'Power On'), ('off', 'Power Off')], default='unknown', max_length=10)),
                ('monitoring_started_at', models.DateTimeField(blank=True, null=True)),
                ('last_heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('last_status_change_at', models.DateTimeField(blank=True, null=True)),
                ('alerting_enabled', models.BooleanField(default=True)),
                ('alerting_failed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Heartbeat',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('received_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeats', to='core.location')),
            ],
            options={
                'verbose_name': 'Heartbeat',
                'verbose_name_plural': 'Heartbeats',
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['location', '-received_at'], name='core_heartb_locatio_f3a505_idx')],
            },
        ),
        migrations.CreateModel(
            name='DiagramMessage',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('telegram_message_id', models.BigIntegerField()),
                ('diagram_date', models.DateField(db_index=True)),
                ('is_pinned', models.BooleanField(default=False)),
                ('last_updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagram_messages', to='core.location')),
            ],
            options={
                'verbose_name': 'Diagram Message',
                'verbose_name_plural': 'Diagram Messages',
                'ordering': ['-diagram_date'],
                'indexes': [models.Index(fields=['location', 'diagram_date'], name='core_diagra_locatio_823783_idx')],
                'unique_together': {('location', 'diagram_date')},
            },
        ),
        migrations.CreateModel(
            name='PowerEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('power_on', 'Power On'), ('power_off', 'Power Off')], max_length=10)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('previous_state_duration_seconds', models.PositiveIntegerField(blank=True, help_text='Duration of the previous power state in seconds', null=True)),
                ('alert_sent', models.BooleanField(default=False)),
                ('alert_sent_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='power_events', to='core.location')),
            ],
            options={
                'verbose_name': 'Power Event',
                'verbose_name_plural': 'Power Events',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['location', 'occurred_at'], name='core_powere_locatio_99fd87_idx')],
            },
        ),
    ]
